route:
  receiver: 'slack'

receivers:
  - name: 'slack'
    slack_configs:
      - send_resolved: true
        username: 'prometheus'
        channel: '#vn-shobo-backend'
        api_url: ${SLACK_HOOK}